name: Build Debian Package

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install devscripts equivs
          sudo mk-build-deps --install debian/control --tool "apt -y" --remove
      - name: Build package
        run: |
          readonly upstream_prefix=LinuxSDK_v
          readonly upstream=$(basename "$upstream_prefix"*)
          version=${upstream/$upstream_prefix/}
          readonly version=${version/.tar*/}
          readonly upstream_ext=.tar${upstream#*.tar}
          ln --verbose --symbolic "${upstream}" "dektec-linux-sdk-${version}${upstream_ext}"
          ln --verbose --symbolic "${upstream}" "dektec-linux-sdk_${version}.orig${upstream_ext}"
          tar --verbose --extract --file="$upstream"
          mv --verbose debian/ LinuxSDK/
          (cd LinuxSDK/ && debuild)
          mkdir --verbose "${{ runner.temp }}/artifact/"
          for deb in *.deb; do mv --verbose "$deb" "${{ runner.temp }}/artifact/${deb%.deb}_${{ matrix.os }}.deb"; done
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ${{ runner.temp }}/artifact/
